#!/bin/bash
# gvamp 0.0.1
# Generated by dx-app-wizard.

main() {

    pip3 install numpy
    pip3 install pandas
    pip3 install argparse

    echo "Value of bed_file: '$bed_file'"
    echo "Value of bim_file: '$bim_file'"
    echo "Value of phen_file: '$phen_file'"
    echo "Value of iterations: '$iterations'"

    dx download "$bed_file"
    dx download "$bim_file"
    dx download "$phen_file"
    PHEN=$(dx ls "${phen_file}")
    BED=$(dx ls "${bed_file}")
    BIM=$(dx ls "${bim_file}")
    M=$(wc -l < ${BIM})
    N=$(wc -l < ${PHEN})

    mkdir estimates
    
    echo ${PHEN}
    echo ${BED}
    echo ${BIM}
    echo ${M}
    echo ${N}
    
    ls -lh
    
    main_real \
        --model linear \
        --run-mode infere \
        --bim-file ${BIM} \
        --bed-file ${BED} \
        --phen-files ${PHEN} \
        --N ${N} \
        --Mt ${M} \
        --out-dir estimates/ \
        --out-name ${out} \
        --iterations ${iterations} \
        --num-mix-comp 4 \
        --probs 0.95,0.02,0.02,0.01 \
        --vars 0.00000,0.0001,0.001,0.01 \
        --learn-vars 1 \
        --store-pvals 1 \
        --rho 0.1

    python3 postprocess.py  --pval estimates/${out}_pvals.bin \
                			--bim ${BIM} \
                            --xhat estimates/${out}_it_${iterations}.bin \
                            --out-name ${out} \
                            --M ${M}

    ls -lh

    marker_estimates=$(dx upload ${out}.gvamp --brief)

    dx-jobutil-add-output marker_estimates "$marker_estimates" --class=file
}
