#=======================================
# To be edited by the configure script
#
ARCH	  = EDIT_ARCH
ROOTDIR   = EDIT_ROOTDIR
BUILDDIR  = EDIT_BUILDDIR
SOURCEDIR = EDIT_SOURCEDIR
LIBFS     = EDIT_LIBFS
#=======================================


setup_file = ${ROOTDIR}/setup/Make.$(ARCH)
include $(setup_file)

EXEC	= gmrm

BINDIR    = $(BUILDDIR)

SOURCES  := $(wildcard $(SOURCEDIR)/*.cpp)

OBJS	:= $(patsubst $(SOURCEDIR)/%.cpp, $(BUILDDIR)/%.o, $(SOURCES))
DEPS	:= $(patsubst $(SOURCEDIR)/%.cpp, $(BUILDDIR)/%.d, $(SOURCES))

LIBS      = -lz $(LIBFS)

.PHONY: all clean

all: gmrm

gmrm: $(BINDIR)/$(EXEC)

$(BINDIR)/$(EXEC): $(OBJS)
	$(MPICXX) $(CXXFLAGS) $^ -o $@ $(LIBS)

$(BUILDDIR)/%.o: $(SOURCEDIR)/%.cpp $(ROOTDIR)/Makefile
	$(MPICXX) $(CXXFLAGS) -MMD -MP -c $< -o $@

-include $(DEPS)

clean:
	rm -vf $(BUILDDIR)/*.o $(BUILDDIR)/*.d $(BINDIR)/$(EXEC)
